"""initial PostgreSQL schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-02
"""

from alembic import op

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    for statement in sql.split(";"):
        statement = statement.strip()
        if statement:
            op.execute(statement)


def upgrade() -> None:
    _execute_statements(
        """
        CREATE TABLE app_user (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          display_name VARCHAR(64) NOT NULL,
          phone VARCHAR(32),
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE category (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(64) NOT NULL,
          parent_id INTEGER NOT NULL DEFAULT 0,
          level INTEGER NOT NULL DEFAULT 1,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE brand (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(64) NOT NULL UNIQUE,
          logo_url VARCHAR(512),
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE attribute_key (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          category_id INTEGER NOT NULL REFERENCES category(id),
          name VARCHAR(64) NOT NULL,
          is_spec BOOLEAN NOT NULL DEFAULT false,
          is_filter BOOLEAN NOT NULL DEFAULT false
        );
        CREATE INDEX idx_attribute_key_category_id ON attribute_key(category_id);
        CREATE UNIQUE INDEX uq_attribute_key_category_name ON attribute_key(category_id, name);

        CREATE TABLE attribute_value (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          attr_key_id INTEGER NOT NULL REFERENCES attribute_key(id),
          value VARCHAR(128) NOT NULL
        );
        CREATE INDEX idx_attribute_value_key_id ON attribute_value(attr_key_id);
        CREATE UNIQUE INDEX uq_attribute_value_key_value ON attribute_value(attr_key_id, value);

        CREATE TABLE spu (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          category_id INTEGER NOT NULL REFERENCES category(id),
          brand_id INTEGER NOT NULL REFERENCES brand(id),
          title VARCHAR(255) NOT NULL,
          sub_title VARCHAR(255),
          detail_html TEXT,
          status INTEGER NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_spu_category_brand ON spu(category_id, brand_id);

        CREATE TABLE sku (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          spu_id BIGINT NOT NULL REFERENCES spu(id),
          title VARCHAR(255) NOT NULL,
          price NUMERIC(10, 2) NOT NULL,
          stock INTEGER NOT NULL DEFAULT 0,
          specs_json JSONB,
          image_url VARCHAR(512),
          status INTEGER NOT NULL DEFAULT 1,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_sku_spu_id ON sku(spu_id);

        CREATE TABLE goods_attribute_relation (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          spu_id BIGINT NOT NULL REFERENCES spu(id),
          sku_id BIGINT NOT NULL DEFAULT 0,
          attr_key_id INTEGER NOT NULL REFERENCES attribute_key(id),
          attr_value_id BIGINT NOT NULL REFERENCES attribute_value(id)
        );
        CREATE INDEX idx_goods_attribute_spu_sku ON goods_attribute_relation(spu_id, sku_id);
        CREATE INDEX idx_goods_attribute_value ON goods_attribute_relation(attr_value_id);

        CREATE TABLE order_info (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL REFERENCES app_user(id),
          total_amount NUMERIC(10, 2) NOT NULL,
          pay_amount NUMERIC(10, 2) NOT NULL,
          freight_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
          pay_type INTEGER NOT NULL DEFAULT 0,
          status INTEGER NOT NULL DEFAULT 1,
          receiver_name VARCHAR(64) NOT NULL,
          receiver_phone VARCHAR(32) NOT NULL,
          receiver_address VARCHAR(512) NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          pay_at TIMESTAMPTZ,
          delivery_at TIMESTAMPTZ
        );
        CREATE INDEX idx_order_info_user_id ON order_info(user_id);
        CREATE INDEX idx_order_info_created_at ON order_info(created_at);

        CREATE TABLE order_item (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id BIGINT NOT NULL REFERENCES order_info(id),
          spu_id BIGINT NOT NULL REFERENCES spu(id),
          sku_id BIGINT NOT NULL REFERENCES sku(id),
          sku_name VARCHAR(255) NOT NULL,
          sku_specs JSONB,
          sku_image VARCHAR(512),
          price NUMERIC(10, 2) NOT NULL,
          quantity INTEGER NOT NULL
        );
        CREATE INDEX idx_order_item_order_id ON order_item(order_id);

        CREATE TABLE order_logistics (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id BIGINT NOT NULL UNIQUE REFERENCES order_info(id),
          express_company VARCHAR(64),
          express_code VARCHAR(32),
          logistic_no VARCHAR(64),
          status INTEGER NOT NULL DEFAULT 0,
          trace_json JSONB,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_order_logistics_logistic_no ON order_logistics(logistic_no);

        CREATE TABLE after_sales_ticket (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL REFERENCES app_user(id),
          order_id BIGINT NOT NULL REFERENCES order_info(id),
          order_item_id BIGINT NOT NULL REFERENCES order_item(id),
          ticket_type VARCHAR(32) NOT NULL,
          reason VARCHAR(255) NOT NULL,
          description TEXT,
          status VARCHAR(32) NOT NULL DEFAULT 'submitted',
          evidence_json JSONB,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_after_sales_user_id ON after_sales_ticket(user_id);
        CREATE INDEX idx_after_sales_order_id ON after_sales_ticket(order_id);

        CREATE TABLE after_sales_event (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ticket_id BIGINT NOT NULL REFERENCES after_sales_ticket(id),
          actor VARCHAR(32) NOT NULL,
          event_type VARCHAR(64) NOT NULL,
          note TEXT,
          metadata_json JSONB,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_after_sales_event_ticket_id ON after_sales_event(ticket_id);

        CREATE TABLE conversation (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL REFERENCES app_user(id),
          title VARCHAR(128) NOT NULL DEFAULT '新会话',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_conversation_user_id ON conversation(user_id);

        CREATE TABLE message (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          conversation_id BIGINT NOT NULL REFERENCES conversation(id),
          role VARCHAR(32) NOT NULL,
          content TEXT NOT NULL,
          metadata_json JSONB,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_message_conversation_id ON message(conversation_id);

        CREATE TABLE agent_run (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          conversation_id BIGINT NOT NULL REFERENCES conversation(id),
          status VARCHAR(32) NOT NULL DEFAULT 'running',
          intent VARCHAR(64),
          state_json JSONB,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          completed_at TIMESTAMPTZ
        );
        CREATE INDEX idx_agent_run_conversation_id ON agent_run(conversation_id);

        CREATE TABLE tool_call (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          agent_run_id BIGINT NOT NULL REFERENCES agent_run(id),
          tool_name VARCHAR(64) NOT NULL,
          input_json JSONB,
          output_json JSONB,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_tool_call_agent_run_id ON tool_call(agent_run_id);

        CREATE TABLE memory_fact (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL REFERENCES app_user(id),
          key VARCHAR(64) NOT NULL,
          value TEXT NOT NULL,
          confidence DOUBLE PRECISION NOT NULL DEFAULT 0.7,
          source_message_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_memory_fact_user_id ON memory_fact(user_id);
        CREATE INDEX idx_memory_fact_key ON memory_fact(key);

        CREATE TABLE knowledge_document (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title VARCHAR(255) NOT NULL,
          document_type VARCHAR(64) NOT NULL,
          content TEXT NOT NULL,
          chroma_collection VARCHAR(128),
          chroma_id VARCHAR(128),
          metadata_json JSONB,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DROP TABLE IF EXISTS knowledge_document CASCADE;
        DROP TABLE IF EXISTS memory_fact CASCADE;
        DROP TABLE IF EXISTS tool_call CASCADE;
        DROP TABLE IF EXISTS agent_run CASCADE;
        DROP TABLE IF EXISTS message CASCADE;
        DROP TABLE IF EXISTS conversation CASCADE;
        DROP TABLE IF EXISTS after_sales_event CASCADE;
        DROP TABLE IF EXISTS after_sales_ticket CASCADE;
        DROP TABLE IF EXISTS order_logistics CASCADE;
        DROP TABLE IF EXISTS order_item CASCADE;
        DROP TABLE IF EXISTS order_info CASCADE;
        DROP TABLE IF EXISTS goods_attribute_relation CASCADE;
        DROP TABLE IF EXISTS sku CASCADE;
        DROP TABLE IF EXISTS spu CASCADE;
        DROP TABLE IF EXISTS attribute_value CASCADE;
        DROP TABLE IF EXISTS attribute_key CASCADE;
        DROP TABLE IF EXISTS brand CASCADE;
        DROP TABLE IF EXISTS category CASCADE;
        DROP TABLE IF EXISTS app_user CASCADE;
        """
    )
